// apps/web-svelte/src/lib/components/GlyphManager.svelte
<!-- Glyph Manager Component - For uploading and managing custom glyphs -->
<script lang="ts">
  import { glyphs, setCustomGlyph, getGlyph, getGlyphContent, resetGlyphToDefault } from '$lib/stores/glyphs.svelte';
  import { Button } from '$lib/components/ui/button/index.js';
  import { Input } from '$lib/components/ui/input/index.js';
  import * as Dialog from '$lib/components/ui/dialog/index.js';
  
  let { embedded = false } = $props();
  
  let open = $state(false);
  let selectedGlyphId = $state<string | null>(null);
  let uploadError = $state<string | null>(null);
  let failedGlyphFiles = $state<Record<string, boolean>>({});
  
  // Get all glyphs grouped by type
  const glyphsByType = $derived({
    planet: Object.values(glyphs).filter(g => g.type === 'planet'),
    zodiac: Object.values(glyphs).filter(g => g.type === 'zodiac'),
    aspect: Object.values(glyphs).filter(g => g.type === 'aspect'),
    custom: Object.values(glyphs).filter(g => g.isCustom),
  });
  
  function handleFileUpload(event: Event, glyphId: string) {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    if (!file) return;
    
    // Validate it's an SVG
    if (!file.name.endsWith('.svg') && !file.type.includes('svg')) {
      uploadError = 'Please upload an SVG file';
      return;
    }
    
    uploadError = null;
    
    // Read file content
    const reader = new FileReader();
    reader.onload = (e) => {
      const svgContent = e.target?.result as string;
      if (svgContent) {
        const glyph = getGlyph(glyphId);
        setCustomGlyph(
          glyphId,
          glyph?.name || glyphId,
          svgContent,
          glyph?.type || 'custom',
          file.name
        );
        selectedGlyphId = null;
      }
    };
    reader.onerror = () => {
      uploadError = 'Failed to read file';
    };
    reader.readAsText(file);
  }
  
  function resetGlyph(glyphId: string) {
    resetGlyphToDefault(glyphId);
  }
</script>

{#snippet glyphManagerContent()}
  {#if uploadError}
    <div class="text-sm text-destructive mb-4">{uploadError}</div>
  {/if}
  
  <!-- Planets -->
  <div class="mb-6">
    <h3 class="text-sm font-semibold mb-3">Planets</h3>
    <div class="flex flex-wrap gap-2">
      {#each glyphsByType.planet as glyph}
        {@const glyphView = getGlyphContent(glyph.id)}
        <div class="flex items-center justify-between p-2 border rounded grow basis-[260px] min-w-[240px]">
          <div class="flex items-center gap-2">
            {#if glyphView.type === 'svg'}
              <span class="inline-block w-6 h-6">{@html glyphView.content}</span>
            {:else if glyphView.type === 'file'}
              {#if failedGlyphFiles[`p:${glyph.id}:${glyphView.content}`]}
                <span class="text-2xl">{glyphView.fallback || glyph.name.charAt(0).toUpperCase()}</span>
              {:else}
                <img
                  src={glyphView.content}
                  alt={glyph.name}
                  style={`width:${glyphView.size}px;height:${glyphView.size}px;`}
                  onerror={() => {
                    failedGlyphFiles[`p:${glyph.id}:${glyphView.content}`] = true;
                    failedGlyphFiles = { ...failedGlyphFiles };
                  }}
                />
              {/if}
            {:else}
              <span class="text-2xl">{glyphView.content}</span>
            {/if}
            <span class="text-sm">{glyph.name}</span>
            {#if glyph.isCustom}
              <span class="text-xs text-muted-foreground">(custom)</span>
            {/if}
          </div>
          <div class="flex gap-1">
            <label class="cursor-pointer">
              <Input
                type="file"
                accept=".svg,image/svg+xml"
                class="hidden"
                onchange={(e) => handleFileUpload(e, glyph.id)}
              />
              <Button variant="ghost" size="sm" type="button">Upload</Button>
            </label>
            {#if glyph.isCustom}
              <Button variant="ghost" size="sm" onclick={() => resetGlyph(glyph.id)}>Reset</Button>
            {/if}
          </div>
        </div>
      {/each}
    </div>
  </div>
  
  <!-- Zodiac Signs -->
  <div class="mb-6">
    <h3 class="text-sm font-semibold mb-3">Zodiac Signs</h3>
    <div class="flex flex-wrap gap-2">
      {#each glyphsByType.zodiac as glyph}
        {@const glyphView = getGlyphContent(glyph.id)}
        <div class="flex items-center justify-between p-2 border rounded grow basis-[260px] min-w-[240px]">
          <div class="flex items-center gap-2">
            {#if glyphView.type === 'svg'}
              <span class="inline-block w-6 h-6">{@html glyphView.content}</span>
            {:else if glyphView.type === 'file'}
              {#if failedGlyphFiles[`z:${glyph.id}:${glyphView.content}`]}
                <span class="text-2xl">{glyphView.fallback || glyph.name.charAt(0).toUpperCase()}</span>
              {:else}
                <img
                  src={glyphView.content}
                  alt={glyph.name}
                  style={`width:${glyphView.size}px;height:${glyphView.size}px;`}
                  onerror={() => {
                    failedGlyphFiles[`z:${glyph.id}:${glyphView.content}`] = true;
                    failedGlyphFiles = { ...failedGlyphFiles };
                  }}
                />
              {/if}
            {:else}
              <span class="text-2xl">{glyphView.content}</span>
            {/if}
            <span class="text-sm">{glyph.name}</span>
            {#if glyph.isCustom}
              <span class="text-xs text-muted-foreground">(custom)</span>
            {/if}
          </div>
          <div class="flex gap-1">
            <label class="cursor-pointer">
              <Input
                type="file"
                accept=".svg,image/svg+xml"
                class="hidden"
                onchange={(e) => handleFileUpload(e, glyph.id)}
              />
              <Button variant="ghost" size="sm" type="button">Upload</Button>
            </label>
            {#if glyph.isCustom}
              <Button variant="ghost" size="sm" onclick={() => resetGlyph(glyph.id)}>Reset</Button>
            {/if}
          </div>
        </div>
      {/each}
    </div>
  </div>
  <!-- Aspects -->
  <div class="mb-6">
    <h3 class="text-sm font-semibold mb-3">Aspects</h3>
    <div class="flex flex-wrap gap-2">
      {#each glyphsByType.aspect as glyph}
        {@const glyphView = getGlyphContent(glyph.id)}
        <div class="flex items-center justify-between p-2 border rounded grow basis-[260px] min-w-[240px]">
          <div class="flex items-center gap-2">
            {#if glyphView.type === 'svg'}
              <span class="inline-block w-6 h-6">{@html glyphView.content}</span>
            {:else if glyphView.type === 'file'}
              {#if failedGlyphFiles[`a:${glyph.id}:${glyphView.content}`]}
                <span class="text-2xl">{glyphView.fallback || glyph.name.charAt(0).toUpperCase()}</span>
              {:else}
                <img
                  src={glyphView.content}
                  alt={glyph.name}
                  style={`width:${glyphView.size}px;height:${glyphView.size}px;`}
                  onerror={() => {
                    failedGlyphFiles[`a:${glyph.id}:${glyphView.content}`] = true;
                    failedGlyphFiles = { ...failedGlyphFiles };
                  }}
                />
              {/if}
            {:else}
              <span class="text-2xl">{glyphView.content}</span>
            {/if}
            <span class="text-sm">{glyph.name}</span>
            {#if glyph.isCustom}
              <span class="text-xs text-muted-foreground">(custom)</span>
            {/if}
          </div>
          <div class="flex gap-1">
            <label class="cursor-pointer">
              <Input
                type="file"
                accept=".svg,image/svg+xml"
                class="hidden"
                onchange={(e) => handleFileUpload(e, glyph.id)}
              />
              <Button variant="ghost" size="sm" type="button">Upload</Button>
            </label>
            {#if glyph.isCustom}
              <Button variant="ghost" size="sm" onclick={() => resetGlyph(glyph.id)}>Reset</Button>
            {/if}
          </div>
        </div>
      {/each}
    </div>
  </div>
{/snippet}

{#if embedded}
  <div class="space-y-3 rounded-md border p-3 max-h-[56vh] overflow-auto">
    <div class="text-sm font-medium opacity-90">Glyphs management</div>
    <div class="text-xs text-muted-foreground">
      Upload custom SVG glyphs to replace default symbols.
    </div>
    {@render glyphManagerContent()}
  </div>
{:else}
  <Dialog.Root bind:open>
    <Dialog.Trigger>
      <Button variant="outline" size="sm">Manage Glyphs</Button>
    </Dialog.Trigger>
    <Dialog.Content class="max-w-2xl max-h-[80vh] overflow-y-auto">
      <Dialog.Header>
        <Dialog.Title>Glyph Management</Dialog.Title>
        <Dialog.Description>
          Upload custom SVG glyphs to replace default symbols. SVG files only.
        </Dialog.Description>
      </Dialog.Header>
      {@render glyphManagerContent()}
      <Dialog.Footer>
        <Button onclick={() => open = false}>Close</Button>
      </Dialog.Footer>
    </Dialog.Content>
  </Dialog.Root>
{/if}

// apps/web-react/src/app/components/glyph-manager.tsx
import { useState, type ChangeEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { AstrologyGlyph } from '@/ui/astrology-glyph';
import { normalizeGlyphId, ZODIAC_IDS, type AstrologyGlyphSetId } from '@/lib/astrology/glyphs';
import {
	OBSERVABLE_OBJECTS,
	OBSERVABLE_OBJECT_CATEGORY_LABELS,
	getObservableCategoryLabel,
	getObservableObjectLabel,
	type ObservableObjectCategory
} from '@/lib/astrology/observableObjects';
import { ASPECT_ROWS, ASPECT_GLYPHS } from '@/lib/astrology/aspects';
import { resetCustomGlyph, setCustomGlyph, useCustomGlyphOverrides } from '@/lib/astrology/customGlyphs';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './ui/accordion';
import { Button } from './ui/button';

type GlyphDomain = 'planet' | 'zodiac' | 'aspect';

type GlyphManagerRowData = { id: string; label: string; domain: GlyphDomain; fallback: string };

type GlyphManagerGroup = { key: string; label: string; rows: GlyphManagerRowData[] };

/** Exotic/large groups collapsed by default, mirroring `BodySelector`. */
const COLLAPSED_BY_DEFAULT = new Set<string>([
	'asteroids',
	'sensitive_points',
	'geocentric_nodes',
	'trans_neptunian',
	'fixed_stars',
	'hypothetical'
]);

function titleCase(id: string): string {
	return id
		.split('_')
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join(' ');
}

function useGlyphManagerGroups(): GlyphManagerGroup[] {
	const { t } = useTranslation();

	const zodiacGroup: GlyphManagerGroup = {
		key: 'zodiac',
		label: t('observable_category_zodiac', { defaultValue: 'Zodiac Signs' }),
		rows: ZODIAC_IDS.map((id) => ({
			id,
			label: titleCase(id),
			domain: 'zodiac' as const,
			fallback: id.slice(0, 2).toUpperCase()
		}))
	};

	const bodyCategories = Object.keys(OBSERVABLE_OBJECT_CATEGORY_LABELS) as ObservableObjectCategory[];
	const bodyGroups: GlyphManagerGroup[] = bodyCategories.map((category) => ({
		key: category,
		label: getObservableCategoryLabel(category, t),
		rows: OBSERVABLE_OBJECTS.filter((item) => item.category === category).map((item) => ({
			id: item.id,
			label: getObservableObjectLabel(item, t),
			domain: 'planet' as const,
			fallback: item.icon
		}))
	}));

	const aspectGroup: GlyphManagerGroup = {
		key: 'aspects',
		label: t('observable_category_aspects', { defaultValue: 'Aspects' }),
		rows: ASPECT_ROWS.map((row) => ({
			id: row.id,
			label: t(row.labelKey, { defaultValue: titleCase(row.id) }),
			domain: 'aspect' as const,
			fallback: ASPECT_GLYPHS[row.id] ?? row.id.slice(0, 3)
		}))
	};

	return [zodiacGroup, ...bodyGroups, aspectGroup].filter((group) => group.rows.length > 0);
}

function GlyphManagerRow({
	row,
	glyphSet,
	isCustom
}: {
	row: GlyphManagerRowData;
	glyphSet: AstrologyGlyphSetId;
	isCustom: boolean;
}) {
	const [error, setError] = useState<string | null>(null);

	function handleUpload(event: ChangeEvent<HTMLInputElement>) {
		const file = event.target.files?.[0];
		event.target.value = '';
		if (!file) return;
		if (!file.name.toLowerCase().endsWith('.svg') && file.type !== 'image/svg+xml') {
			setError('Please upload an SVG file');
			return;
		}
		setError(null);
		const reader = new FileReader();
		reader.onload = (loadEvent) => {
			const svg = loadEvent.target?.result;
			if (typeof svg === 'string') {
				setCustomGlyph(row.id, row.label, svg, file.name);
			}
		};
		reader.onerror = () => setError('Failed to read file');
		reader.readAsText(file);
	}

	return (
		<div className="flex min-w-[240px] grow basis-[260px] items-center justify-between gap-2 rounded-lg border border-[color:var(--theme-panel-border)] p-2">
			<div className="flex min-w-0 items-center gap-2">
				<AstrologyGlyph
					glyphId={row.id}
					glyphSet={glyphSet}
					domain={row.domain}
					fallback={row.fallback}
					size={22}
				/>
				<span className="truncate text-sm">{row.label}</span>
				{isCustom ? (
					<span className="text-xs text-[color:var(--theme-content-muted)]">(custom)</span>
				) : null}
			</div>
			<div className="flex shrink-0 items-center gap-1">
				<label className="cursor-pointer">
					<input type="file" accept=".svg,image/svg+xml" className="hidden" onChange={handleUpload} />
					<Button variant="ghost" size="sm" type="button" asChild>
						<span>Upload</span>
					</Button>
				</label>
				{isCustom ? (
					<Button
						variant="ghost"
						size="sm"
						type="button"
						onClick={() => resetCustomGlyph(row.id)}
					>
						Reset
					</Button>
				) : null}
			</div>
			{error ? <p className="w-full text-xs text-red-500">{error}</p> : null}
		</div>
	);
}

export function GlyphManager({ glyphSet }: { glyphSet: AstrologyGlyphSetId }) {
	const groups = useGlyphManagerGroups();
	const overrides = useCustomGlyphOverrides();
	const defaultOpen = groups.map((g) => g.key).filter((key) => !COLLAPSED_BY_DEFAULT.has(key));

	return (
		<div className="space-y-2">
			<p className="text-xs text-[color:var(--theme-content-muted)]">
				Upload a custom SVG to replace any glyph below. Uploads are stored on this device only.
			</p>
			<Accordion type="multiple" defaultValue={defaultOpen} className="w-full">
				{groups.map((group) => (
					<AccordionItem key={group.key} value={group.key}>
						<AccordionTrigger>{group.label}</AccordionTrigger>
						<AccordionContent>
							<div className="flex flex-wrap gap-2 pt-1">
								{group.rows.map((row) => (
									<GlyphManagerRow
										key={row.id}
										row={row}
										glyphSet={glyphSet}
										isCustom={Boolean(overrides[normalizeGlyphId(row.id)])}
									/>
								))}
							</div>
						</AccordionContent>
					</AccordionItem>
				))}
			</Accordion>
		</div>
	);
}
