// apps/web-svelte/src/lib/components/ui/checkbox/checkbox.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	type CheckboxProps = WithElementRef<
		Omit<HTMLInputAttributes, "type"> & {
			indeterminate?: boolean;
		},
		HTMLInputElement
	>;

	let {
		ref = $bindable<HTMLInputElement | null>(null),
		checked = $bindable(false),
		indeterminate = $bindable(false),
		class: className,
		...restProps
	}: CheckboxProps = $props();

	$effect(() => {
		if (ref) {
			ref.indeterminate = Boolean(indeterminate);
		}
	});
</script>

<input
	bind:this={ref}
	data-slot="checkbox"
	type="checkbox"
	class={cn(
		"peer size-4 shrink-0 rounded-sm border border-input bg-background shadow-xs transition-[color,box-shadow] outline-none",
		"checked:border-primary checked:bg-primary checked:text-primary-foreground",
		"focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
		"aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
		"disabled:cursor-not-allowed disabled:opacity-50",
		className
	)}
	bind:checked
	{...restProps}
/>

// apps/web-react/src/app/components/ui/checkbox.tsx
'use client';

import * as React from 'react';
import * as CheckboxPrimitive from '@radix-ui/react-checkbox';
import { CheckIcon, MinusIcon } from 'lucide-react';

import { cn } from './utils';

function Checkbox({ className, ...props }: React.ComponentProps<typeof CheckboxPrimitive.Root>) {
	return (
		<CheckboxPrimitive.Root
			data-slot="checkbox"
			className={cn(
				'peer bg-input-background dark:bg-input/30 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground dark:data-[state=checked]:bg-primary data-[state=checked]:border-primary focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive size-4 shrink-0 rounded-md border shadow-xs transition-shadow outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50',
				className
			)}
			{...props}
		>
			<CheckboxPrimitive.Indicator
				data-slot="checkbox-indicator"
				className="flex items-center justify-center text-current transition-none"
			>
				{props.checked === 'indeterminate' ? (
					<MinusIcon className="size-3.5" />
				) : (
					<CheckIcon className="size-3.5" />
				)}
			</CheckboxPrimitive.Indicator>
		</CheckboxPrimitive.Root>
	);
}

export { Checkbox };
