// apps/web-react/src/app/components/mode-switcher.tsx
import { Tabs, TabsList, TabsTrigger } from './ui/tabs';
import { cn } from './ui/utils';

export type ModeSwitcherOption<T extends string> = {
	value: T;
	label: string;
};

type ModeSwitcherProps<T extends string> = {
	value: T;
	options: readonly ModeSwitcherOption<T>[];
	onValueChange: (value: T) => void;
	ariaLabel: string;
	className?: string;
	listClassName?: string;
};

type ModeSwitcherListProps<T extends string> = {
	options: readonly ModeSwitcherOption<T>[];
	ariaLabel: string;
	className?: string;
};

export function ModeSwitcherList<T extends string>({
	options,
	ariaLabel,
	className
}: ModeSwitcherListProps<T>) {
	return (
		<TabsList
			aria-label={ariaLabel}
			className={cn(
				'grid h-10 w-full border border-[color:var(--theme-panel-border)] bg-[color:var(--theme-soft-bg)]',
				className
			)}
			style={{ gridTemplateColumns: `repeat(${options.length}, minmax(0, 1fr))` }}
		>
			{options.map((option) => (
				<TabsTrigger key={option.value} value={option.value}>
					{option.label}
				</TabsTrigger>
			))}
		</TabsList>
	);
}

export function ModeSwitcher<T extends string>({
	value,
	options,
	onValueChange,
	ariaLabel,
	className,
	listClassName
}: ModeSwitcherProps<T>) {
	return (
		<Tabs value={value} onValueChange={(next) => onValueChange(next as T)} className={className}>
			<ModeSwitcherList options={options} ariaLabel={ariaLabel} className={listClassName} />
		</Tabs>
	);
}

// apps/web-svelte/src/lib/components/ModeSwitcher.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button/index.js';
  import { cn } from '$lib/utils';

  type ModeSwitcherOption = {
    value: string;
    label: string;
  };

  interface Props {
    value: string;
    options: readonly ModeSwitcherOption[];
    ariaLabel: string;
    onValueChange?: (value: string) => void;
    class?: string;
  }

  let { value = $bindable(), options, ariaLabel, onValueChange, class: className }: Props = $props();

  function select(next: string) {
    value = next;
    onValueChange?.(next);
  }
</script>

<div
  class={cn('grid h-10 gap-1 rounded-md border bg-muted p-1', className)}
  style:grid-template-columns={`repeat(${options.length}, minmax(0, 1fr))`}
  role="radiogroup"
  aria-label={ariaLabel}
>
  {#each options as option (option.value)}
    <Button
      type="button"
      variant={value === option.value ? 'default' : 'ghost'}
      class="h-full min-w-0 px-2"
      aria-pressed={value === option.value}
      onclick={() => select(option.value)}
    >
      <span class="truncate">{option.label}</span>
    </Button>
  {/each}
</div>
