// apps/web-react/src/app/components/revolution-view.tsx
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { AppMainContentRoot } from './app-main-content';
import type { Theme } from './astrology-sidebar';
import { useAppFormFieldTheme } from './form-field-theme';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Separator } from './ui/separator';
import { Switch } from './ui/switch';
import { cn } from './ui/utils';

type RevolutionKind = 'solar' | 'lunar' | 'relative';
type RevolutionScope = 'return' | 'quarters' | 'fraction';

const REVOLUTION_KINDS: RevolutionKind[] = ['solar', 'lunar', 'relative'];
const REVOLUTION_SCOPES: RevolutionScope[] = ['return', 'quarters', 'fraction'];

export function RevolutionView({ theme }: { theme: Theme }) {
	const { t } = useTranslation();
	const ft = useAppFormFieldTheme(theme);
	const [kind, setKind] = useState<RevolutionKind>('solar');
	const [includeTransReturn, setIncludeTransReturn] = useState(false);
	const [scope, setScope] = useState<RevolutionScope>('return');
	const [fraction, setFraction] = useState('10');
	const [customPeriod, setCustomPeriod] = useState(false);
	const [dateFrom, setDateFrom] = useState('');
	const [dateTo, setDateTo] = useState('');

	const calculate = () => {
		toast.success(t('revolution_submitted'), {
			description: t(`revolution_kind_${kind}`)
		});
	};

	return (
		<AppMainContentRoot className={ft.formPageBg}>
			<form
				className="mx-auto w-full max-w-[520px] py-5 md:py-10"
				onSubmit={(event) => {
					event.preventDefault();
					calculate();
				}}
			>
				<section>
					<Label className={cn('mb-3 text-xs tracking-[0.08em] uppercase', ft.muted)}>
						{t('revolution_kind_label')}
					</Label>
					<Select value={kind} onValueChange={(value) => setKind(value as RevolutionKind)}>
						<SelectTrigger className={cn(ft.selectTrigger, 'min-h-11 rounded-full')}>
							<SelectValue />
						</SelectTrigger>
						<SelectContent className={ft.selectContent}>
							{REVOLUTION_KINDS.map((option) => (
								<SelectItem key={option} value={option} className={ft.selectItem}>
									{t(`revolution_kind_${option}`)}
								</SelectItem>
							))}
						</SelectContent>
					</Select>
				</section>

				<Separator className="my-6 bg-[color:var(--theme-panel-border)]" />

				<section className="flex items-center justify-between gap-4">
					<Label htmlFor="trans-revolution" className={cn('text-sm', ft.title)}>
						{t('revolution_trans_return')}
					</Label>
					<Switch
						id="trans-revolution"
						checked={includeTransReturn}
						onCheckedChange={setIncludeTransReturn}
						className={cn(
							'data-[state=checked]:bg-[color:var(--theme-accent)]',
							ft.switchUnchecked
						)}
					/>
				</section>

				<Separator className="my-6 bg-[color:var(--theme-panel-border)]" />

				<fieldset>
					<legend className={cn('mb-4 text-xs tracking-[0.08em] uppercase', ft.muted)}>
						{t('revolution_scope_label')}
					</legend>
					<div className="space-y-4">
						{REVOLUTION_SCOPES.map((option) => (
							<label key={option} className="flex cursor-pointer items-center gap-3">
								<input
									type="radio"
									name="revolution-scope"
									value={option}
									checked={scope === option}
									onChange={() => setScope(option)}
									className="size-4 accent-[var(--theme-accent)]"
								/>
								<span className={cn('text-sm', scope === option ? ft.title : ft.muted)}>
									{t(`revolution_scope_${option}`)}
								</span>
								{option === 'fraction' ? (
									<span
										className={cn(
											'ml-1 flex items-center gap-1.5 text-sm transition-opacity',
											scope !== 'fraction' && 'pointer-events-none opacity-35'
										)}
									>
										<span>1</span>
										<span className={ft.muted}>/</span>
										<Input
											aria-label={t('revolution_fraction_denominator')}
											inputMode="numeric"
											value={fraction}
											onChange={(event) => setFraction(event.target.value.replace(/\D/g, ''))}
											disabled={scope !== 'fraction'}
											className={cn(ft.inputCompact, 'w-12 px-1 text-center')}
										/>
									</span>
								) : null}
							</label>
						))}
					</div>
				</fieldset>

				<Separator className="my-6 bg-[color:var(--theme-panel-border)]" />

				<section className="mb-9">
					<div className="flex items-center justify-between gap-4">
						<Label htmlFor="revolution-period" className={cn('text-sm', ft.title)}>
							{t('revolution_set_period')}
						</Label>
						<Switch
							id="revolution-period"
							checked={customPeriod}
							onCheckedChange={setCustomPeriod}
							className={cn(
								'data-[state=checked]:bg-[color:var(--theme-accent)]',
								ft.switchUnchecked
							)}
						/>
					</div>
					<div
						className={cn(
							'grid overflow-hidden transition-all duration-200 sm:grid-cols-2 sm:gap-3',
							customPeriod ? 'mt-4 max-h-32 gap-3 opacity-100' : 'max-h-0 opacity-0'
						)}
						aria-hidden={!customPeriod}
					>
						<div>
							<Label
								htmlFor="revolution-date-from"
								className={cn('mb-2 text-xs uppercase', ft.muted)}
							>
								{t('revolution_date_from')}
							</Label>
							<Input
								id="revolution-date-from"
								type="date"
								value={dateFrom}
								onChange={(event) => setDateFrom(event.target.value)}
								className={ft.inputCompact}
								tabIndex={customPeriod ? 0 : -1}
							/>
						</div>
						<div>
							<Label
								htmlFor="revolution-date-to"
								className={cn('mb-2 text-xs uppercase', ft.muted)}
							>
								{t('revolution_date_to')}
							</Label>
							<Input
								id="revolution-date-to"
								type="date"
								value={dateTo}
								onChange={(event) => setDateTo(event.target.value)}
								className={ft.inputCompact}
								tabIndex={customPeriod ? 0 : -1}
							/>
						</div>
					</div>
				</section>

				<Button type="submit" className={cn(ft.footerPrimary, 'h-11 w-full')}>
					{t('revolution_calculate')}
				</Button>
			</form>
		</AppMainContentRoot>
	);
}

// apps/web-svelte/src/lib/components/RevolutionView.svelte
<script lang="ts">
  import { t } from '$lib/i18n/index.svelte';
  import { Button } from '$lib/components/ui/button/index.js';
  import { Input } from '$lib/components/ui/input/index.js';
  import { Label } from '$lib/components/ui/label/index.js';
  import * as Select from '$lib/components/ui/select/index.js';
  import { Separator } from '$lib/components/ui/separator/index.js';

  type RevolutionKind = 'solar' | 'lunar' | 'relative';
  type RevolutionScope = 'return' | 'quarters' | 'fraction';

  const revolutionKinds: RevolutionKind[] = ['solar', 'lunar', 'relative'];
  const revolutionScopes: RevolutionScope[] = ['return', 'quarters', 'fraction'];

  let kind = $state<RevolutionKind>('solar');
  let includeTransReturn = $state(false);
  let scope = $state<RevolutionScope>('return');
  let fraction = $state('10');
  let customPeriod = $state(false);
  let dateFrom = $state('');
  let dateTo = $state('');
  let submitted = $state(false);

  const selectedKindLabel = $derived(t(`revolution_kind_${kind}`, {}, kind));

  function submit(event: SubmitEvent) {
    event.preventDefault();
    submitted = true;
  }
</script>

<div class="h-full w-full overflow-y-auto rounded-md border bg-card text-card-foreground shadow-sm">
  <form class="mx-auto w-full max-w-[520px] px-4 py-10 sm:px-6" onsubmit={submit}>
    <section>
      <Label class="mb-3 block text-xs uppercase tracking-[0.08em] text-muted-foreground">
        {t('revolution_kind_label', {}, 'Revolution type')}
      </Label>
      <Select.Root type="single" bind:value={kind}>
        <Select.Trigger class="h-11 w-full rounded-full px-4">
          {selectedKindLabel}
        </Select.Trigger>
        <Select.Content>
          <Select.Group>
            {#each revolutionKinds as option}
              <Select.Item value={option} label={t(`revolution_kind_${option}`, {}, option)}>
                {t(`revolution_kind_${option}`, {}, option)}
              </Select.Item>
            {/each}
          </Select.Group>
        </Select.Content>
      </Select.Root>
    </section>

    <Separator class="my-6" />

    <section class="flex items-center justify-between gap-4">
      <Label for="svelte-trans-revolution">{t('revolution_trans_return', {}, 'Trans-revolution')}</Label>
      <button
        id="svelte-trans-revolution"
        type="button"
        role="switch"
        aria-checked={includeTransReturn}
        aria-label={t('revolution_trans_return', {}, 'Trans-revolution')}
        class="relative inline-flex h-[22px] w-[38px] shrink-0 items-center rounded-full transition-colors focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none"
        class:bg-primary={includeTransReturn}
        class:bg-muted-foreground={!includeTransReturn}
        onclick={() => (includeTransReturn = !includeTransReturn)}
      >
        <span class="block size-4 rounded-full bg-background shadow transition-transform {includeTransReturn ? 'translate-x-[19px]' : 'translate-x-[3px]'}"></span>
      </button>
    </section>

    <Separator class="my-6" />

    <fieldset>
      <legend class="mb-4 text-xs uppercase tracking-[0.08em] text-muted-foreground">
        {t('revolution_scope_label', {}, 'Revolution')}
      </legend>
      <div class="space-y-4">
        {#each revolutionScopes as option}
          <label class="flex cursor-pointer items-center gap-3">
            <input class="size-4 accent-primary" type="radio" name="svelte-revolution-scope" value={option} bind:group={scope} />
            <span class:text-muted-foreground={scope !== option} class="text-sm">
              {t(`revolution_scope_${option}`, {}, option)}
            </span>
            {#if option === 'fraction'}
              <span class="ml-1 flex items-center gap-1.5 text-sm" class:pointer-events-none={scope !== 'fraction'} class:opacity-35={scope !== 'fraction'}>
                <span>1</span><span class="text-muted-foreground">/</span>
                <Input
                  aria-label={t('revolution_fraction_denominator', {}, 'Fraction denominator')}
                  inputmode="numeric"
                  value={fraction}
                  oninput={(event) => (fraction = event.currentTarget.value.replace(/\D/g, ''))}
                  disabled={scope !== 'fraction'}
                  class="h-8 w-12 px-1 text-center"
                />
              </span>
            {/if}
          </label>
        {/each}
      </div>
    </fieldset>

    <Separator class="my-6" />

    <section class="mb-9">
      <div class="flex items-center justify-between gap-4">
        <Label for="svelte-revolution-period">{t('revolution_set_period', {}, 'Set period')}</Label>
        <button
          id="svelte-revolution-period"
          type="button"
          role="switch"
          aria-checked={customPeriod}
          aria-label={t('revolution_set_period', {}, 'Set period')}
          class="relative inline-flex h-[22px] w-[38px] shrink-0 items-center rounded-full transition-colors focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none"
          class:bg-primary={customPeriod}
          class:bg-muted-foreground={!customPeriod}
          onclick={() => (customPeriod = !customPeriod)}
        >
          <span class="block size-4 rounded-full bg-background shadow transition-transform {customPeriod ? 'translate-x-[19px]' : 'translate-x-[3px]'}"></span>
        </button>
      </div>

      <div class="grid overflow-hidden transition-all duration-200 sm:grid-cols-2 sm:gap-3" class:mt-4={customPeriod} class:max-h-32={customPeriod} class:gap-3={customPeriod} class:opacity-100={customPeriod} class:max-h-0={!customPeriod} class:opacity-0={!customPeriod} aria-hidden={!customPeriod}>
        <div>
          <Label for="svelte-revolution-from" class="mb-2 block text-xs uppercase text-muted-foreground">{t('revolution_date_from', {}, 'From')}</Label>
          <Input id="svelte-revolution-from" type="date" bind:value={dateFrom} tabindex={customPeriod ? 0 : -1} />
        </div>
        <div>
          <Label for="svelte-revolution-to" class="mb-2 block text-xs uppercase text-muted-foreground">{t('revolution_date_to', {}, 'To')}</Label>
          <Input id="svelte-revolution-to" type="date" bind:value={dateTo} tabindex={customPeriod ? 0 : -1} />
        </div>
      </div>
    </section>

    <Button type="submit" class="h-11 w-full rounded-xl">{t('revolution_calculate', {}, 'Calculate revolution')}</Button>
    {#if submitted}
      <p class="mt-3 text-center text-sm text-muted-foreground" role="status">
        {t('revolution_submitted', {}, 'Revolution calculation is ready')} · {selectedKindLabel}
      </p>
    {/if}
  </form>
</div>
